//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 My2DGraphics.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_My2DGraphicsTYPE            130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDI_ICON1                       319
#define IDI_ICON2                       320
#define IDI_ICON3                       321
#define IDI_ICON4                       322
#define IDI_ICON5                       323
#define IDI_ICON6                       324
#define IDI_ICON7                       325
#define IDI_ICON8                       326
#define IDI_ICON9                       327
#define IDI_ICON10                      328
#define IDI_ICON11                      329
#define IDI_ICON12                      330
#define IDI_ICON13                      331
#define IDI_ICON14                      332
#define IDI_ICON15                      333
#define IDI_ICON16                      334
#define IDI_ICON17                      335
#define IDI_ICON18                      336
#define IDI_ICON19                      337
#define IDI_ICON20                      338
#define IDI_ICON21                      339
#define IDB_BITMAP1                     341
#define ID_32771                        32771
#define ID_LINE                         32772
#define ID_32773                        32773
#define ID_ELLIPSE                      32774
#define ID_32775                        32775
#define ID_32776                        32776
#define ID_                             32777
#define ID_ANTILINE                     32778
#define ID_32779                        32779
#define ID_EDGEFILLPOLY                 32780
#define ID_AETFILLPOLY                  32781
#define ID_EDGEFILLPOLY2                32782
#define ID_32790                        32790
#define ID_SEEDFILLPOLY                 32791
#define ID_BUTTON32793                  32793
#define ID_BUTTON32794                  32794
#define ID_CHOOSE_COLOR                 32795
#define ID_BUTTON32798                  32798
#define ID_LOADFIG                      32801
#define ID_LEFT                         32802
#define ID_RIGHT                        32803
#define ID_UP                           32804
#define ID_DOWN                         32805
#define ID_INCREASE                     32806
#define ID_DECREASE                     32807
#define ID_XPOSITIVE                    32808
#define ID_YNEGATIVE                    32810
#define ID_REFLECTX                     32811
#define ID_REFLICTO                     32812
#define ID_ROTATE_CLOCK                 32813
#define ID_ROTATE_ANTI_CLOCK            32814
#define ID_RESET                        32815
#define ID_XNEGATIVE                    32817
#define ID_REFLECTY                     32819
#define ID_YPOSITIVE                    32820

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        342
#define _APS_NEXT_COMMAND_VALUE         32821
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
